#!/bin/sh
python createdb.py
python hellodjango2scoops/manage.py syncdb --settings=hellodjango2scoops.settings.production --noinput
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/volatile/static
python hellodjango2scoops/manage.py collectstatic --settings=hellodjango2scoops.settings.production --noinput
